# Site settings
title: blog.makky.io
email: makky.4d6b.3f5@gmail.com
description: blog.makky.io はMakky（小林 正樹:Masaki Kobayashi）のブログです。JavaScriptをはじめとするWebアプリケーション開発や写真、日々の出来事について書きます。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.makky.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: RE

include: ['_pages']

exclude: ['Dockerfile', 'Gemfile', 'Gemfile.lock', 'README.md']

# Build settings
markdown: kramdown

permalink: /articles/:year/:month/:day/:title

gems:
  - jekyll-sitemap
