timezone: Asia/Tokyo

gems:
  - jekyll-sitemap

sass:
  style: compressed

include:
  - _pages

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

exclude:
  - vendor
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - images-src

title: blog.makky.io

email: makky.4d6b.3f5@gmail.com

description: >
  blog.makky.io はMakkyのブログです。

baseurl: ''

url: 'http://blog.makky.io'

markdown: kramdown

permalink: /articles/:year/:month/:day/:title/

account:
  twitter: https://twitter.com/_Makky_
  facebook: https://www.facebook.com/masaki.kobayashi.1485
  github: https://github.com/makky3939
  slideshare: http://www.slideshare.net/masakikobayashi1485
  steam: http://steamcommunity.com/profiles/76561198000450118
  google_plus: https://plus.google.com/u/0/+MasakiKobayashi_makky_/posts

project:
  repository: https://github.com/makky3939/blog.makky.io
  issues: https://github.com/makky3939/blog.makky.io/issues

links:
  blog_makky_io: http://blog.makky.io
  www_makky_io: http://www.makky.io
  about: http://blog.makky.io/about
